### ISSUE TITLE
Error executing command

### ISSUE THREAD

**Issue by xCss** [davidanger/MSCOMM32#1]
Error executing this command(As Administrator):
> regsvr32 /i C:\WINDOWS\SysWOW64\MSCOMM32.OCX

> Windows 10 x64 Enterprise Edition

[![微信截图_20190315102144](https://user-images.githubusercontent.com/10877162/54403791-4b4c9300-470c-11e9-907a-a0ca87c1a286.png)](https://user-images.githubusercontent.com/10877162/54403791-4b4c9300-470c-11e9-907a-a0ca87c1a286.png)

**Comment by davidanger** [comment]
可以先不用管报错 流程跑完试试 如果还不行的话 再联系

**Comment by davidanger** [comment]
记得以管理员身份运行

**Comment by la-huan** [comment]
同样遇到这个问题，但能用
